set serveroutput on

DECLARE
	NUID varchar2(50);
	JOB_ID number;
	QUESTION_DESCRIPTION long;
	DIFFICULTY varchar2(10);
	TECHNOLOGY_LIST_1 varchar2(10);
	TECHNOLOGY_LIST_2 varchar2(10);
	rows_affected number;



BEGIN

	NUID := '&NUID';
	JOB_ID := '&JOB_ID';
	QUESTION_DESCRIPTION := '&QUESTION_DESCRIPTION';
	DIFFICULTY := '&DIFFICULTY';
	TECHNOLOGY_LIST_1 := '&TECHNOLOGY_LIST_1';
	TECHNOLOGY_LIST_2 := '&TECHNOLOGY_LIST_2';


POST_INTERVIEW_QUESTION(NUID,JOB_ID,QUESTION_DESCRIPTION,DIFFICULTY,TECHNOLOGY_LIST_1,TECHNOLOGY_LIST_2,rows_affected);
dbms_output.put_line(ra || 'Question Posted');

END;