--------------------------------------------------------
--  File created - Saturday-April-27-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMPANY
--------------------------------------------------------

  CREATE TABLE "C##PROJECT_ADMIN"."COMPANY" 
   (	"COMPANY_ID" VARCHAR2(20 BYTE), 
	"COLUMN1" VARCHAR2(40 BYTE), 
	"COLUMN2" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOUBT_POSTED_LOG
--------------------------------------------------------

  CREATE TABLE "C##PROJECT_ADMIN"."DOUBT_POSTED_LOG" 
   (	"DOUBT_ID" NUMBER, 
	"NUID" NUMBER, 
	"POSTED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOUBT_RESPONSE
--------------------------------------------------------

  CREATE TABLE "C##PROJECT_ADMIN"."DOUBT_RESPONSE" 
   (	"RESPONSE_ID" NUMBER, 
	"DOUBT_ID" NUMBER, 
	"RESPONSE_DESCRIPTION" LONG, 
	"RESPONSE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOUBTS
--------------------------------------------------------

  CREATE TABLE "C##PROJECT_ADMIN"."DOUBTS" 
   (	"DOUBT_ID" NUMBER, 
	"NUID" CHAR(9 BYTE), 
	"DOUBT_DESCRIPTION" LONG, 
	"DOMAIN" VARCHAR2(40 BYTE), 
	"POSTED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  NO INMEMORY ("DOUBT_DESCRIPTION") ;
--------------------------------------------------------
--  DDL for Table FACULTY_SUBJECT_EXPERTISE
--------------------------------------------------------

  CREATE TABLE "C##PROJECT_ADMIN"."FACULTY_SUBJECT_EXPERTISE" 
   (	"NUID" CHAR(9 BYTE), 
	"SUBJECT_EXPERTISE" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INT_QUES_POSTED_LOG
--------------------------------------------------------

  CREATE TABLE "C##PROJECT_ADMIN"."INT_QUES_POSTED_LOG" 
   (	"QUESTION_ID" NUMBER, 
	"NUID" NUMBER, 
	"POSTED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INT_QUES_RESPONSE
--------------------------------------------------------

  CREATE TABLE "C##PROJECT_ADMIN"."INT_QUES_RESPONSE" 
   (	"RESPONSE_ID" NUMBER, 
	"INT_QUES_ID" NUMBER, 
	"RESPONSE_DESCRIPTION" LONG, 
	"RESPONSE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  NO INMEMORY ("RESPONSE_DESCRIPTION") ;
--------------------------------------------------------
--  DDL for Table INTERVIEW_QUESTIONS
--------------------------------------------------------

  CREATE TABLE "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS" 
   (	"QUESTION_ID" NUMBER, 
	"NUID" CHAR(9 BYTE), 
	"JOB_ID" NUMBER, 
	"QUESTION_DESCRIPTION" LONG, 
	"DIFFICULTY_LEVEL" VARCHAR2(30 BYTE), 
	"TECHNOLOGIES" "C##PROJECT_ADMIN"."TECHNOLOGY_LIST_TYPE" , 
	"DOMAIN" VARCHAR2(30 BYTE), 
	"POSTED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JOB_DETAILS
--------------------------------------------------------

  CREATE TABLE "C##PROJECT_ADMIN"."JOB_DETAILS" 
   (	"JOB_ID" NUMBER, 
	"JOB_TITLE" VARCHAR2(40 BYTE), 
	"COMPANY_NAME" VARCHAR2(40 BYTE), 
	"DOMAIN" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POSITION
--------------------------------------------------------

  CREATE TABLE "C##PROJECT_ADMIN"."POSITION" 
   (	"POSITION_ID" NUMBER, 
	"POSITION_TITLE" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STUDENT_FACULTY
--------------------------------------------------------

  CREATE TABLE "C##PROJECT_ADMIN"."STUDENT_FACULTY" 
   (	"NUID" CHAR(9 BYTE), 
	"COOP_ADVISOR" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_INFO
--------------------------------------------------------

  CREATE TABLE "C##PROJECT_ADMIN"."USER_INFO" 
   (	"NUID" CHAR(9 BYTE), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROJECT_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Table USER_LOGIN_LOG
--------------------------------------------------------

  CREATE TABLE "C##PROJECT_ADMIN"."USER_LOGIN_LOG" 
   (	"USERNAME" VARCHAR2(100 BYTE), 
	"LOGIN_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_SIGNUP_LOG
--------------------------------------------------------

  CREATE TABLE "C##PROJECT_ADMIN"."USER_SIGNUP_LOG" 
   (	"USERNAME" VARCHAR2(30 BYTE), 
	"DESIGNATION" VARCHAR2(30 BYTE), 
	"SIGNUP_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into C##PROJECT_ADMIN.COMPANY
SET DEFINE OFF;
REM INSERTING into C##PROJECT_ADMIN.DOUBT_POSTED_LOG
SET DEFINE OFF;
Insert into C##PROJECT_ADMIN.DOUBT_POSTED_LOG (DOUBT_ID,NUID,POSTED_DATE) values (2,1889030,to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.DOUBT_POSTED_LOG (DOUBT_ID,NUID,POSTED_DATE) values (4,1889030,to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.DOUBT_POSTED_LOG (DOUBT_ID,NUID,POSTED_DATE) values (6,1888728,to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.DOUBT_POSTED_LOG (DOUBT_ID,NUID,POSTED_DATE) values (5,1889030,to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.DOUBT_POSTED_LOG (DOUBT_ID,NUID,POSTED_DATE) values (7,1888735,to_date('26-APR-19','DD-MON-RR'));
REM INSERTING into C##PROJECT_ADMIN.DOUBT_RESPONSE
SET DEFINE OFF;
Insert into C##PROJECT_ADMIN.DOUBT_RESPONSE (RESPONSE_ID,DOUBT_ID,RESPONSE_DESCRIPTION,RESPONSE_DATE) values (21,5,'A clustered index defines the order in which data is physically stored in a table. Table data can be sorted in only way, therefore, there can be only one clustered index per table',to_date('27-APR-19','DD-MON-RR'));
REM INSERTING into C##PROJECT_ADMIN.DOUBTS
SET DEFINE OFF;
Insert into C##PROJECT_ADMIN.DOUBTS (DOUBT_ID,NUID,DOUBT_DESCRIPTION,DOMAIN,POSTED_DATE) values (4,'001889030','How to select non na rows from a Dataset in R?','DATA SCIENCE',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.DOUBTS (DOUBT_ID,NUID,DOUBT_DESCRIPTION,DOMAIN,POSTED_DATE) values (5,'001889030','What is a clustered/non clustered index?','BUSINESS INTELLIGENCE',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.DOUBTS (DOUBT_ID,NUID,DOUBT_DESCRIPTION,DOMAIN,POSTED_DATE) values (6,'1888728  ','What is a JavaScript callback function?','WEB DEVELOPMENT',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.DOUBTS (DOUBT_ID,NUID,DOUBT_DESCRIPTION,DOMAIN,POSTED_DATE) values (7,'1888735  ','How to write a function that divides two numbers without using the divide / operator?','SOFTWARE ENGINEERING',to_date('26-APR-19','DD-MON-RR'));
REM INSERTING into C##PROJECT_ADMIN.FACULTY_SUBJECT_EXPERTISE
SET DEFINE OFF;
Insert into C##PROJECT_ADMIN.FACULTY_SUBJECT_EXPERTISE (NUID,SUBJECT_EXPERTISE) values ('1888813  ','Business Intelligence');
Insert into C##PROJECT_ADMIN.FACULTY_SUBJECT_EXPERTISE (NUID,SUBJECT_EXPERTISE) values ('1888814  ','Data Science');
Insert into C##PROJECT_ADMIN.FACULTY_SUBJECT_EXPERTISE (NUID,SUBJECT_EXPERTISE) values ('1888815  ','Software Engineering');
Insert into C##PROJECT_ADMIN.FACULTY_SUBJECT_EXPERTISE (NUID,SUBJECT_EXPERTISE) values ('1888816  ','Web Development');
REM INSERTING into C##PROJECT_ADMIN.INT_QUES_POSTED_LOG
SET DEFINE OFF;
Insert into C##PROJECT_ADMIN.INT_QUES_POSTED_LOG (QUESTION_ID,NUID,POSTED_DATE) values (31,1888713,to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INT_QUES_POSTED_LOG (QUESTION_ID,NUID,POSTED_DATE) values (32,1888713,to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INT_QUES_POSTED_LOG (QUESTION_ID,NUID,POSTED_DATE) values (30,1888715,to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INT_QUES_POSTED_LOG (QUESTION_ID,NUID,POSTED_DATE) values (33,1888713,to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INT_QUES_POSTED_LOG (QUESTION_ID,NUID,POSTED_DATE) values (34,1888713,to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INT_QUES_POSTED_LOG (QUESTION_ID,NUID,POSTED_DATE) values (35,1888713,to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INT_QUES_POSTED_LOG (QUESTION_ID,NUID,POSTED_DATE) values (36,1888728,to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INT_QUES_POSTED_LOG (QUESTION_ID,NUID,POSTED_DATE) values (37,1888728,to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INT_QUES_POSTED_LOG (QUESTION_ID,NUID,POSTED_DATE) values (38,1888737,to_date('26-APR-19','DD-MON-RR'));
REM INSERTING into C##PROJECT_ADMIN.INT_QUES_RESPONSE
SET DEFINE OFF;
Insert into C##PROJECT_ADMIN.INT_QUES_RESPONSE (RESPONSE_ID,INT_QUES_ID,RESPONSE_DESCRIPTION,RESPONSE_DATE) values (41,21,'Conditional formatting is a feature of Excel which allows you to apply a format to a cell or a range of cells based on certain criteria',to_date('27-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INT_QUES_RESPONSE (RESPONSE_ID,INT_QUES_ID,RESPONSE_DESCRIPTION,RESPONSE_DATE) values (21,21,'Conditional Formatting (CF) is a tool that allows you to apply formats to a cell or range of cells, and have that formatting change depending on the value of the cell or the value of a formula.',to_date('26-APR-19','DD-MON-RR'));
REM INSERTING into C##PROJECT_ADMIN.INTERVIEW_QUESTIONS
SET DEFINE OFF;
Insert into C##PROJECT_ADMIN.INTERVIEW_QUESTIONS (QUESTION_ID,NUID,JOB_ID,QUESTION_DESCRIPTION,DIFFICULTY_LEVEL,TECHNOLOGIES,DOMAIN,POSTED_DATE) values (33,'1888713  ',11468,'In jQuery, describe how the selector syntax works for the click function.','Medium',C##PROJECT_ADMIN.TECHNOLOGY_LIST_TYPE(C##PROJECT_ADMIN.TECHNOLOGY_TYPE('JQuery'), C##PROJECT_ADMIN.TECHNOLOGY_TYPE('Web Development')),'Web Development',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INTERVIEW_QUESTIONS (QUESTION_ID,NUID,JOB_ID,QUESTION_DESCRIPTION,DIFFICULTY_LEVEL,TECHNOLOGIES,DOMAIN,POSTED_DATE) values (30,'1888715  ',10241,'What is the data structure in data warehouse?','Medium',C##PROJECT_ADMIN.TECHNOLOGY_LIST_TYPE(C##PROJECT_ADMIN.TECHNOLOGY_TYPE('ETL'), C##PROJECT_ADMIN.TECHNOLOGY_TYPE('Data Warehousing')),'Business Intelligence',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INTERVIEW_QUESTIONS (QUESTION_ID,NUID,JOB_ID,QUESTION_DESCRIPTION,DIFFICULTY_LEVEL,TECHNOLOGIES,DOMAIN,POSTED_DATE) values (31,'1888713  ',10680,'What is logistic regression? What is Bayesian Heirarchical modeling?ÿ','Easy',C##PROJECT_ADMIN.TECHNOLOGY_LIST_TYPE(C##PROJECT_ADMIN.TECHNOLOGY_TYPE('Machine Learning'), C##PROJECT_ADMIN.TECHNOLOGY_TYPE('Regression')),'Data Science',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INTERVIEW_QUESTIONS (QUESTION_ID,NUID,JOB_ID,QUESTION_DESCRIPTION,DIFFICULTY_LEVEL,TECHNOLOGIES,DOMAIN,POSTED_DATE) values (32,'1888713  ',10346,'What is an abstract class and why would you use it?','Medium',C##PROJECT_ADMIN.TECHNOLOGY_LIST_TYPE(C##PROJECT_ADMIN.TECHNOLOGY_TYPE('Java'), C##PROJECT_ADMIN.TECHNOLOGY_TYPE('OOP')),'Software Engineering',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INTERVIEW_QUESTIONS (QUESTION_ID,NUID,JOB_ID,QUESTION_DESCRIPTION,DIFFICULTY_LEVEL,TECHNOLOGIES,DOMAIN,POSTED_DATE) values (34,'1888713  ',11741,'1. talk about the flow of working with react 2. schema design 3. RESTful api 4. algo questions like the typical matching parenthesis problem','Medium',C##PROJECT_ADMIN.TECHNOLOGY_LIST_TYPE(C##PROJECT_ADMIN.TECHNOLOGY_TYPE('React'), C##PROJECT_ADMIN.TECHNOLOGY_TYPE('Web Development')),'Web Development',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INTERVIEW_QUESTIONS (QUESTION_ID,NUID,JOB_ID,QUESTION_DESCRIPTION,DIFFICULTY_LEVEL,TECHNOLOGIES,DOMAIN,POSTED_DATE) values (21,'001889030',11070,'What is conditional formatting in Tableau?','Easy',C##PROJECT_ADMIN.TECHNOLOGY_LIST_TYPE(C##PROJECT_ADMIN.TECHNOLOGY_TYPE('Tableau'), C##PROJECT_ADMIN.TECHNOLOGY_TYPE('Data Visualization')),'Business Intelligence',to_date('24-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INTERVIEW_QUESTIONS (QUESTION_ID,NUID,JOB_ID,QUESTION_DESCRIPTION,DIFFICULTY_LEVEL,TECHNOLOGIES,DOMAIN,POSTED_DATE) values (35,'1888713  ',11341,'Difference between Swift and Objective C','Easy',C##PROJECT_ADMIN.TECHNOLOGY_LIST_TYPE(C##PROJECT_ADMIN.TECHNOLOGY_TYPE('Swift'), C##PROJECT_ADMIN.TECHNOLOGY_TYPE('iOS Development')),'Web Development',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INTERVIEW_QUESTIONS (QUESTION_ID,NUID,JOB_ID,QUESTION_DESCRIPTION,DIFFICULTY_LEVEL,TECHNOLOGIES,DOMAIN,POSTED_DATE) values (36,'1888728  ',11682,'MVC Architecture, Problems with MVC, MVVM architecture, UITableViews, UICollectionViews','Hard',C##PROJECT_ADMIN.TECHNOLOGY_LIST_TYPE(C##PROJECT_ADMIN.TECHNOLOGY_TYPE('MVC'), C##PROJECT_ADMIN.TECHNOLOGY_TYPE('Spring Hibernate')),'Software Engineering',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INTERVIEW_QUESTIONS (QUESTION_ID,NUID,JOB_ID,QUESTION_DESCRIPTION,DIFFICULTY_LEVEL,TECHNOLOGIES,DOMAIN,POSTED_DATE) values (37,'1888728  ',10557,'Given a binary tree with the usual left and right pointers on each node, and additionally a parent pointer, make an algorithm to discover the closest ancestor to 2 nodes on the tree.','Hard',C##PROJECT_ADMIN.TECHNOLOGY_LIST_TYPE(C##PROJECT_ADMIN.TECHNOLOGY_TYPE('Data Structures'), C##PROJECT_ADMIN.TECHNOLOGY_TYPE('Programming')),'Software Engineering',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.INTERVIEW_QUESTIONS (QUESTION_ID,NUID,JOB_ID,QUESTION_DESCRIPTION,DIFFICULTY_LEVEL,TECHNOLOGIES,DOMAIN,POSTED_DATE) values (38,'1888737  ',11712,'Write a program to translate alphanumeric phone number to numbers only','Hard',C##PROJECT_ADMIN.TECHNOLOGY_LIST_TYPE(C##PROJECT_ADMIN.TECHNOLOGY_TYPE('Algorithms'), C##PROJECT_ADMIN.TECHNOLOGY_TYPE('Programming')),'Software Engineering',to_date('26-APR-19','DD-MON-RR'));
REM INSERTING into C##PROJECT_ADMIN.JOB_DETAILS
SET DEFINE OFF;
Insert into C##PROJECT_ADMIN.JOB_DETAILS (JOB_ID,JOB_TITLE,COMPANY_NAME,DOMAIN) values (11070,'Business Intelligence Developer Intern','Nestle','Business Intelligence');
Insert into C##PROJECT_ADMIN.JOB_DETAILS (JOB_ID,JOB_TITLE,COMPANY_NAME,DOMAIN) values (10241,'Business Intelligence Developer Intern','Citigroup','Business Intelligence');
Insert into C##PROJECT_ADMIN.JOB_DETAILS (JOB_ID,JOB_TITLE,COMPANY_NAME,DOMAIN) values (10680,'Data Science Intern','Wal-Mart Stores','Data Science');
Insert into C##PROJECT_ADMIN.JOB_DETAILS (JOB_ID,JOB_TITLE,COMPANY_NAME,DOMAIN) values (10346,'Software Engineering Intern','General Electric','Software Engineering');
Insert into C##PROJECT_ADMIN.JOB_DETAILS (JOB_ID,JOB_TITLE,COMPANY_NAME,DOMAIN) values (11468,'Web Developer Intern','Walt Disney','Web Development');
Insert into C##PROJECT_ADMIN.JOB_DETAILS (JOB_ID,JOB_TITLE,COMPANY_NAME,DOMAIN) values (11741,'Web Developer Intern','Wal-Mart Stores','Web Development');
Insert into C##PROJECT_ADMIN.JOB_DETAILS (JOB_ID,JOB_TITLE,COMPANY_NAME,DOMAIN) values (11712,'Software Engineering Intern','Apple','Software Engineering');
Insert into C##PROJECT_ADMIN.JOB_DETAILS (JOB_ID,JOB_TITLE,COMPANY_NAME,DOMAIN) values (10557,'Software Engineering Intern','Oracle','Software Engineering');
Insert into C##PROJECT_ADMIN.JOB_DETAILS (JOB_ID,JOB_TITLE,COMPANY_NAME,DOMAIN) values (11682,'Software Engineering Intern','Microsoft','Software Engineering');
Insert into C##PROJECT_ADMIN.JOB_DETAILS (JOB_ID,JOB_TITLE,COMPANY_NAME,DOMAIN) values (11341,'Application Developer Intern','BMW Group','Web Development');
REM INSERTING into C##PROJECT_ADMIN.POSITION
SET DEFINE OFF;
Insert into C##PROJECT_ADMIN.POSITION (POSITION_ID,POSITION_TITLE) values (1,'Business Intelligence Developer Intern');
Insert into C##PROJECT_ADMIN.POSITION (POSITION_ID,POSITION_TITLE) values (2,'Data Science Intern');
Insert into C##PROJECT_ADMIN.POSITION (POSITION_ID,POSITION_TITLE) values (3,'Software Engineering Intern');
Insert into C##PROJECT_ADMIN.POSITION (POSITION_ID,POSITION_TITLE) values (4,'Web Developer Intern');
Insert into C##PROJECT_ADMIN.POSITION (POSITION_ID,POSITION_TITLE) values (5,'Application Developer Intern');
REM INSERTING into C##PROJECT_ADMIN.STUDENT_FACULTY
SET DEFINE OFF;
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888713  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888714  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888715  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888716  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888717  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888718  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888719  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888720  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888721  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888722  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888723  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888724  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888725  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888726  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888727  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888728  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888729  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888730  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888731  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888732  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888733  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888734  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888735  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888736  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888737  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888738  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888739  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888740  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888741  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888742  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888743  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888744  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888745  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888746  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888747  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888748  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888749  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888750  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888751  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888752  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888753  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888754  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888755  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888756  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888757  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888758  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888759  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888760  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888761  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888762  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888763  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888764  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888765  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888766  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888767  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888768  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888769  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888770  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888771  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888772  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888773  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888774  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888775  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888776  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888777  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888778  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888779  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888780  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888781  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888782  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888783  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888784  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888785  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888786  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888787  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888788  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888789  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888790  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888791  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888792  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888793  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888794  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888795  ','Maricla Pirozzi');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888796  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888797  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888798  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888799  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888800  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888801  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888802  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888803  ','Jessica Fisher');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888804  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888805  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888806  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888807  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888808  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888809  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888810  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888811  ','Laura Meyer');
Insert into C##PROJECT_ADMIN.STUDENT_FACULTY (NUID,COOP_ADVISOR) values ('1888812  ','Laura Meyer');
REM INSERTING into C##PROJECT_ADMIN.USER_INFO
SET DEFINE OFF;
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('001889031','ABC','DEF','abc@neu.edu','qwerty');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('001889032','Mario','Sulkin','m.sulkin@neu.edu','Mario');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('001889030','sanika','bhagat','san@northeastern.edu','qwe');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888713  ','Maria','Griffin','m.griffin@neu.edu','Maria');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888714  ','Harriet','Little','h.little@neu.edu','Harriet');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888715  ','Rosa','Norton','r.norton@neu.edu','Rosa');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888716  ','Lewis','Vargas','l.vargas@neu.edu','Lewis');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888717  ','Harriet','Anderson','h.anderson@neu.edu','Harriet');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888718  ','Georgie','Brewer','g.brewer@neu.edu','Georgie');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888719  ','Ernest','Hunt','e.hunt@neu.edu','Ernest');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888720  ','Amy','Spencer','a.spencer@neu.edu','Amy');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888721  ','Leila','Page','l.page@neu.edu','Leila');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888722  ','Lelia','Willis','l.willis@neu.edu','Lelia');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888723  ','Sean','Klein','s.klein@neu.edu','Sean');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888724  ','Rebecca','Clarke','r.clarke@neu.edu','Rebecca');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888725  ','Luella','McCormick','l.mccormick@neu.edu','Luella');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888726  ','Mattie','Matthews','m.matthews@neu.edu','Mattie');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888727  ','Inez','Richards','i.richards@neu.edu','Inez');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888728  ','Frank','Jordan','f.jordan@neu.edu','Frank');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888729  ','Nancy','Montgomery','n.montgomery@neu.edu','Nancy');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888730  ','Maurice','Hall','m.hall@neu.edu','Maurice');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888731  ','Jesus','Quinn','j.quinn@neu.edu','Jesus');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888732  ','Henrietta','Casey','h.casey@neu.edu','Henrietta');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888733  ','Winifred','Atkins','w.atkins@neu.edu','Winifred');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888734  ','Edgar','Smith','e.smith@neu.edu','Edgar');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888735  ','Lora','Watkins','l.watkins@neu.edu','Lora');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888736  ','Danny','Barnett','d.barnett@neu.edu','Danny');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888737  ','Sophie','Burton','s.burton@neu.edu','Sophie');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888738  ','Adelaide','Watts','a.watts@neu.edu','Adelaide');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888739  ','Theodore','Ingram','t.ingram@neu.edu','Theodore');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888740  ','Gerald','Drake','g.drake@neu.edu','Gerald');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888741  ','Jesse','Peters','j.peters@neu.edu','Jesse');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888742  ','Theresa','Nguyen','t.nguyen@neu.edu','Theresa');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888743  ','Rosalie','Wolfe','r.wolfe@neu.edu','Rosalie');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888744  ','Lina','Thomas','l.thomas@neu.edu','Lina');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888745  ','Dora','Wong','d.wong@neu.edu','Dora');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888746  ','Alvin','Mendez','a.mendez@neu.edu','Alvin');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888747  ','Johanna','Lloyd','j.lloyd@neu.edu','Johanna');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888748  ','Gilbert','Dixon','g.dixon@neu.edu','Gilbert');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888749  ','Luella','Bishop','l.bishop@neu.edu','Luella');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888750  ','Lina','Hardy','l.hardy@neu.edu','Lina');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888751  ','Miguel','Kelly','m.kelly@neu.edu','Miguel');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888752  ','Calvin','Bridges','c.bridges@neu.edu','Calvin');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888753  ','Rosalie','Nunez','r.nunez@neu.edu','Rosalie');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888754  ','Virginia','Greene','v.greene@neu.edu','Virginia');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888755  ','Stephen','Douglas','s.douglas@neu.edu','Stephen');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888756  ','Hester','Nguyen','h.nguyen@neu.edu','Hester');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888757  ','Maurice','Ford','m.ford@neu.edu','Maurice');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888758  ','Lillian','Watts','l.watts@neu.edu','Lillian');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888759  ','Chad','Thompson','c.thompson@neu.edu','Chad');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888760  ','Earl','Patton','e.patton@neu.edu','Earl');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888761  ','Alta','Tyler','a.tyler@neu.edu','Alta');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888762  ','Lottie','Martin','l.martin@neu.edu','Lottie');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888763  ','Clyde','Griffith','c.griffith@neu.edu','Clyde');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888764  ','Myra','Baker','m.baker@neu.edu','Myra');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888765  ','Leroy','Jordan','l.jordan@neu.edu','Leroy');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888766  ','Philip','Carter','p.carter@neu.edu','Philip');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888767  ','Iva','West','i.west@neu.edu','Iva');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888768  ','Ann','Bowman','a.bowman@neu.edu','Ann');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888769  ','Ina','Garrett','i.garrett@neu.edu','Ina');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888770  ','Oscar','Long','o.long@neu.edu','Oscar');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888771  ','Hettie','Newman','h.newman@neu.edu','Hettie');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888772  ','Rosetta','Quinn','r.quinn@neu.edu','Rosetta');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888773  ','Janie','Woods','j.woods@neu.edu','Janie');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888774  ','Stella','Diaz','s.diaz@neu.edu','Stella');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888775  ','Callie','Hopkins','c.hopkins@neu.edu','Callie');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888776  ','Rosetta','Elliott','r.elliott@neu.edu','Rosetta');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888777  ','Genevieve','Mullins','g.mullins@neu.edu','Genevieve');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888778  ','Della','Bowers','d.bowers@neu.edu','Della');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888779  ','Olive','Jacobs','o.jacobs@neu.edu','Olive');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888780  ','Victoria','Reynolds','v.reynolds@neu.edu','Victoria');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888781  ','Jennie','Sullivan','j.sullivan@neu.edu','Jennie');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888782  ','Jim','Wood','j.wood@neu.edu','Jim');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888783  ','Henrietta','Mason','h.mason@neu.edu','Henrietta');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888784  ','Esther','Carter','e.carter@neu.edu','Esther');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888785  ','Irene','Ford','i.ford@neu.edu','Irene');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888786  ','Allie','Morrison','a.morrison@neu.edu','Allie');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888787  ','Frederick','Allison','f.allison@neu.edu','Frederick');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888788  ','Seth','Hudson','s.hudson@neu.edu','Seth');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888789  ','Ruth','Castillo','r.castillo@neu.edu','Ruth');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888790  ','Jackson','Griffith','j.griffith@neu.edu','Jackson');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888791  ','Chad','Blake','c.blake@neu.edu','Chad');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888792  ','Alejandro','Clark','a.clark@neu.edu','Alejandro');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888793  ','Ronnie','Banks','r.banks@neu.edu','Ronnie');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888794  ','Pearl','Kelley','p.kelley@neu.edu','Pearl');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888795  ','Mabelle','Ward','m.ward@neu.edu','Mabelle');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888796  ','Wesley','Watts','w.watts@neu.edu','Wesley');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888797  ','Jon','Rodriguez','j.rodriguez@neu.edu','Jon');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888798  ','Myrtle','Bowen','m.bowen@neu.edu','Myrtle');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888799  ','Isabella','Perkins','i.perkins@neu.edu','Isabella');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888800  ','Ivan','Griffith','i.griffith@neu.edu','Ivan');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888801  ','Shane','Nelson','s.nelson@neu.edu','Shane');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888802  ','Leona','Lindsey','l.lindsey@neu.edu','Leona');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888803  ','Elsie','Owens','e.owens@neu.edu','Elsie');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888804  ','Frank','Montgomery','f.montgomery@neu.edu','Frank');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888805  ','Rebecca','Lewis','r.lewis@neu.edu','Rebecca');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888806  ','Walter','Turner','w.turner@neu.edu','Walter');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888807  ','Helen','Brooks','h.brooks@neu.edu','Helen');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888808  ','Addie','Huff','a.huff@neu.edu','Addie');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888809  ','Flora','Bell','f.bell@neu.edu','Flora');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888810  ','Lora','Dunn','l.dunn@neu.edu','Lora');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888811  ','Luis','Hammond','l.hammond@neu.edu','Luis');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888812  ','Jesse','Allen','j.allen@neu.edu','Jesse');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888813  ','Rick','Sherman','r.sherman@northeastern.edu','Rick');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888814  ','Nick','Brown','n.brown@northeastern.edu','Nick');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888815  ','Robin','Hillyard','r.hillyard@northeastern.edu','Robin');
Insert into C##PROJECT_ADMIN.USER_INFO (NUID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) values ('1888816  ','Yusuf','Ozbek','y.ozbek@northeastern.edu','Yusuf');
REM INSERTING into C##PROJECT_ADMIN.USER_LOGIN_LOG
SET DEFINE OFF;
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('27-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_LOGIN_LOG (USERNAME,LOGIN_DATE) values ('C##PROJECT_ADMIN',to_date('27-APR-19','DD-MON-RR'));
REM INSERTING into C##PROJECT_ADMIN.USER_SIGNUP_LOG
SET DEFINE OFF;
Insert into C##PROJECT_ADMIN.USER_SIGNUP_LOG (USERNAME,DESIGNATION,SIGNUP_DATE) values ('san@northeastern.edu','Faculty',to_date('24-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_SIGNUP_LOG (USERNAME,DESIGNATION,SIGNUP_DATE) values ('sw@northeastern.edu','Faculty',to_date('26-APR-19','DD-MON-RR'));
Insert into C##PROJECT_ADMIN.USER_SIGNUP_LOG (USERNAME,DESIGNATION,SIGNUP_DATE) values ('m.sulkin@neu.edu','Student',to_date('26-APR-19','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index COMPANY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJECT_ADMIN"."COMPANY_PK" ON "C##PROJECT_ADMIN"."COMPANY" ("COMPANY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DOUBT_RESPONSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJECT_ADMIN"."DOUBT_RESPONSE_PK" ON "C##PROJECT_ADMIN"."DOUBT_RESPONSE" ("RESPONSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DOUBTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJECT_ADMIN"."DOUBTS_PK" ON "C##PROJECT_ADMIN"."DOUBTS" ("DOUBT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FACULTY_SUBJECT_EXPERTISE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJECT_ADMIN"."FACULTY_SUBJECT_EXPERTISE_PK" ON "C##PROJECT_ADMIN"."FACULTY_SUBJECT_EXPERTISE" ("NUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INT_QUES_RESPONSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJECT_ADMIN"."INT_QUES_RESPONSE_PK" ON "C##PROJECT_ADMIN"."INT_QUES_RESPONSE" ("RESPONSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INTERVIEW_QUESTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS_PK" ON "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS" ("QUESTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index JOB_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJECT_ADMIN"."JOB_DETAILS_PK" ON "C##PROJECT_ADMIN"."JOB_DETAILS" ("JOB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POSITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJECT_ADMIN"."POSITION_PK" ON "C##PROJECT_ADMIN"."POSITION" ("POSITION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STUDENT_FACULTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJECT_ADMIN"."STUDENT_FACULTY_PK" ON "C##PROJECT_ADMIN"."STUDENT_FACULTY" ("NUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROJECT_ADMIN"."USER_INFO_PK" ON "C##PROJECT_ADMIN"."USER_INFO" ("NUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger COMPANY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROJECT_ADMIN"."COMPANY_TRG" 
BEFORE INSERT ON COMPANY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COMPANY_ID IS NULL THEN
      SELECT COMPANY_SEQ.NEXTVAL INTO :NEW.COMPANY_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PROJECT_ADMIN"."COMPANY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOUBT_RESPONSE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROJECT_ADMIN"."DOUBT_RESPONSE_TRG" 
BEFORE INSERT ON DOUBT_RESPONSE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.RESPONSE_ID IS NULL THEN
      SELECT DOUBT_RESPONSE_SEQ.NEXTVAL INTO :NEW.RESPONSE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PROJECT_ADMIN"."DOUBT_RESPONSE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOUBTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROJECT_ADMIN"."DOUBTS_TRG" 
BEFORE INSERT ON DOUBTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PROJECT_ADMIN"."DOUBTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOUBT_POSTED_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROJECT_ADMIN"."DOUBT_POSTED_TRIGGER" 
    AFTER INSERT 
    OR DELETE 
    ON DOUBTS
    FOR EACH ROW

	BEGIN
    CASE
    WHEN INSERTING THEN
		INSERT INTO DOUBT_POSTED_LOG values (:new.DOUBT_ID, :new.NUID,:new.POSTED_DATE);
	WHEN DELETING THEN
        DELETE FROM DOUBT_POSTED_LOG WHERE DOUBT_ID = :new.DOUBT_ID;
    END CASE;
	END DOUBT_POSTED_TRIGGER;
/
ALTER TRIGGER "C##PROJECT_ADMIN"."DOUBT_POSTED_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOUBTS_TRG2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROJECT_ADMIN"."DOUBTS_TRG2" 
BEFORE INSERT ON DOUBTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PROJECT_ADMIN"."DOUBTS_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOUBTS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROJECT_ADMIN"."DOUBTS_TRG1" 
BEFORE INSERT ON DOUBTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PROJECT_ADMIN"."DOUBTS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOUBTS_TRG3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROJECT_ADMIN"."DOUBTS_TRG3" 
BEFORE INSERT ON DOUBTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.DOUBT_ID IS NULL THEN
      SELECT DOUBTS_SEQ4.NEXTVAL INTO :NEW.DOUBT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PROJECT_ADMIN"."DOUBTS_TRG3" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INT_QUES_RESPONSE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROJECT_ADMIN"."INT_QUES_RESPONSE_TRG" 
BEFORE INSERT ON INT_QUES_RESPONSE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PROJECT_ADMIN"."INT_QUES_RESPONSE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INT_QUES_RESPONSE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROJECT_ADMIN"."INT_QUES_RESPONSE_TRG1" 
BEFORE INSERT ON INT_QUES_RESPONSE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.RESPONSE_ID IS NULL THEN
      SELECT INT_QUES_RESPONSE_SEQ1.NEXTVAL INTO :NEW.RESPONSE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PROJECT_ADMIN"."INT_QUES_RESPONSE_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INTERVIEW_QUESTIONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS_TRG" 
BEFORE INSERT ON INTERVIEW_QUESTIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INTERVIEW_QUESTIONS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS_TRG1" 
BEFORE INSERT ON INTERVIEW_QUESTIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.QUESTION_ID IS NULL THEN
      SELECT INTERVIEW_QUESTIONS_SEQ2.NEXTVAL INTO :NEW.QUESTION_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INT_QUES_POSTED_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROJECT_ADMIN"."INT_QUES_POSTED_TRIGGER" 
    AFTER INSERT 
    OR DELETE 
    ON INTERVIEW_QUESTIONS
    FOR EACH ROW

	BEGIN
    CASE
    WHEN INSERTING THEN
		INSERT INTO INT_QUES_POSTED_LOG values (:new.QUESTION_ID, :new.NUID,:new.POSTED_DATE);
	WHEN DELETING THEN
        DELETE FROM INT_QUES_POSTED_LOG WHERE QUESTION_ID = :new.QUESTION_ID;
    END CASE;
	END INT_QUES_POSTED_TRIGGER;


/
ALTER TRIGGER "C##PROJECT_ADMIN"."INT_QUES_POSTED_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POSITION_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROJECT_ADMIN"."POSITION_TRG" 
BEFORE INSERT ON POSITION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.POSITION_ID IS NULL THEN
      SELECT POSITION_SEQ.NEXTVAL INTO :NEW.POSITION_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PROJECT_ADMIN"."POSITION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_SIGNUP_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROJECT_ADMIN"."USER_SIGNUP_TRIGGER" 
  AFTER INSERT ON USER_INFO
  FOR EACH ROW

BEGIN
    if (instr(:new.EMAIL,'northeastern.edu')>0) then
    INSERT INTO USER_SIGNUP_LOG values (:new.email, 'Faculty',SYSDATE);
    else 
    INSERT INTO USER_SIGNUP_LOG values (:new.email, 'Student',SYSDATE);
    end if;
END USER_SIGNUP_TRIGGER;
/
ALTER TRIGGER "C##PROJECT_ADMIN"."USER_SIGNUP_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPANY
--------------------------------------------------------

  ALTER TABLE "C##PROJECT_ADMIN"."COMPANY" MODIFY ("COMPANY_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."COMPANY" MODIFY ("COLUMN1" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."COMPANY" MODIFY ("COLUMN2" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."COMPANY" ADD CONSTRAINT "COMPANY_PK" PRIMARY KEY ("COMPANY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOUBT_RESPONSE
--------------------------------------------------------

  ALTER TABLE "C##PROJECT_ADMIN"."DOUBT_RESPONSE" MODIFY ("RESPONSE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."DOUBT_RESPONSE" MODIFY ("DOUBT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."DOUBT_RESPONSE" MODIFY ("RESPONSE_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."DOUBT_RESPONSE" ADD CONSTRAINT "DOUBT_RESPONSE_PK" PRIMARY KEY ("RESPONSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOUBTS
--------------------------------------------------------

  ALTER TABLE "C##PROJECT_ADMIN"."DOUBTS" MODIFY ("DOUBT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."DOUBTS" MODIFY ("NUID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."DOUBTS" ADD CONSTRAINT "DOUBTS_PK" PRIMARY KEY ("DOUBT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##PROJECT_ADMIN"."DOUBTS" MODIFY ("DOUBT_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."DOUBTS" MODIFY ("DOMAIN" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."DOUBTS" ADD CONSTRAINT "DOUBTS_CHK1" CHECK (DOMAIN IN ('BUSINESS INTELLIGENCE', 'DATA SCIENCE', 'DATA ANALYSIS', 'DATA ANALYTICS', 'SOFTWARE ENGINEERING','WEB DEVELOPMENT')) ENABLE;
--------------------------------------------------------
--  Constraints for Table FACULTY_SUBJECT_EXPERTISE
--------------------------------------------------------

  ALTER TABLE "C##PROJECT_ADMIN"."FACULTY_SUBJECT_EXPERTISE" MODIFY ("NUID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."FACULTY_SUBJECT_EXPERTISE" MODIFY ("SUBJECT_EXPERTISE" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."FACULTY_SUBJECT_EXPERTISE" ADD CONSTRAINT "FACULTY_SUBJECT_EXPERTISE_PK" PRIMARY KEY ("NUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INT_QUES_RESPONSE
--------------------------------------------------------

  ALTER TABLE "C##PROJECT_ADMIN"."INT_QUES_RESPONSE" MODIFY ("RESPONSE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."INT_QUES_RESPONSE" MODIFY ("INT_QUES_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."INT_QUES_RESPONSE" ADD CONSTRAINT "INT_QUES_RESPONSE_PK" PRIMARY KEY ("RESPONSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INTERVIEW_QUESTIONS
--------------------------------------------------------

  ALTER TABLE "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS" MODIFY ("NUID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS" MODIFY ("QUESTION_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS" MODIFY ("DIFFICULTY_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS" MODIFY ("TECHNOLOGIES" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS" ADD CONSTRAINT "DIFFICULTY_LEVEL_CHK_IQ" CHECK (DIFFICULTY_LEVEL IN ('Easy', 'easy', 'EASY', 'Medium', 'medium', 'MEDIUM', 'Hard', 'hard', 'HARD')) ENABLE;
  ALTER TABLE "C##PROJECT_ADMIN"."INTERVIEW_QUESTIONS" ADD CONSTRAINT "INTERVIEW_QUESTIONS_PK" PRIMARY KEY ("QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JOB_DETAILS
--------------------------------------------------------

  ALTER TABLE "C##PROJECT_ADMIN"."JOB_DETAILS" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."JOB_DETAILS" MODIFY ("JOB_TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."JOB_DETAILS" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."JOB_DETAILS" ADD CONSTRAINT "JOB_DETAILS_PK" PRIMARY KEY ("JOB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##PROJECT_ADMIN"."JOB_DETAILS" MODIFY ("DOMAIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSITION
--------------------------------------------------------

  ALTER TABLE "C##PROJECT_ADMIN"."POSITION" MODIFY ("POSITION_ID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."POSITION" MODIFY ("POSITION_TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."POSITION" ADD CONSTRAINT "POSITION_PK" PRIMARY KEY ("POSITION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT_FACULTY
--------------------------------------------------------

  ALTER TABLE "C##PROJECT_ADMIN"."STUDENT_FACULTY" MODIFY ("NUID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."STUDENT_FACULTY" MODIFY ("COOP_ADVISOR" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."STUDENT_FACULTY" ADD CONSTRAINT "STUDENT_FACULTY_PK" PRIMARY KEY ("NUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##PROJECT_ADMIN"."STUDENT_FACULTY" ADD CONSTRAINT "STUDENT_FACULTY_CHK" CHECK (COOP_ADVISOR IN ('Maricla Pirozzi', 'Laura Meyer', 'Jessica Fisher')) ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_INFO
--------------------------------------------------------

  ALTER TABLE "C##PROJECT_ADMIN"."USER_INFO" MODIFY ("NUID" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."USER_INFO" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."USER_INFO" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."USER_INFO" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."USER_INFO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##PROJECT_ADMIN"."USER_INFO" ADD CONSTRAINT "USER_INFO_PK" PRIMARY KEY ("NUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
